
import databaseConnection.DatabaseUtil;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author shahd
 */
public class labTests extends javax.swing.JFrame {

    /**
     * Creates new form labTests
     */
    int labId;
    public labTests() {
        initComponents();
        try {
            fetchLabTests();
        } catch (SQLException ex) {
            Logger.getLogger(labTests.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     public labTests(int labID) {
         labId = labID;
        initComponents();
        try {
            fetchLabTests();
        } catch (SQLException ex) {
            Logger.getLogger(labTests.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        labTestTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labTestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TestID", "Test Name", "Test cost ", "Test Duration"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(labTestTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void fetchLabTests() throws SQLException {
    java.sql.Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;

    try {
        // Use DatabaseUtil to get the connection
        conn = DatabaseUtil.getConnection();
       
   
        
        // SQL query to retrieve data including nurse salary
          String fetchTestData = "SELECT t.TEST_ID AS testId, \n" +
"       t.TEST_NAME AS testName, \n" +
"       t.TEST_DURATION AS testDuration, \n" +
"       t.TEST_COST AS testCost, \n" +
"       l.NAME AS labName \n" +
"FROM tests t \n" +
"JOIN labs l ON t.LAB_ID = l.LAB_ID\n" +
"WHERE l.LAB_ID = 4";
              
        
        // Creating a DefaultTableModel to hold the table data
            DefaultTableModel model = (DefaultTableModel) labTestTable.getModel();
        model.setRowCount(0); // Clear existing rows if any

        pstmt = conn.prepareStatement(fetchTestData);
        rs = pstmt.executeQuery();
        
        // Fetching data from ResultSet and adding to JTable
         while (rs.next()) {
            int testId = rs.getInt("testId");
            String testName = rs.getString("testName");
            int testDuration = rs.getInt("testDuration");
            double testCost = rs.getDouble("testCost");
            String labName = rs.getString("labName");

            // Adding row to table model
            model.addRow(new Object[]{testId, testName, testDuration, testCost, labName});
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    } finally {
        // Close resources
        DatabaseUtil.close(conn, pstmt, rs);
    }
}
 public void fetchTests() throws SQLException {
    java.sql.Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;

    try {
        // Use DatabaseUtil to get the connection
        conn = DatabaseUtil.getConnection();
       
   
        
        // SQL query to retrieve data including nurse salary
          String fetchTestData = "SELECT t.TEST_ID AS testId, " +
                               "t.TEST_NAME AS testName, " +
                               "t.TEST_DURATION AS testDuration, " +
                               "t.TEST_COST AS testCost, " +
                               "l.NAME AS labName " +
                               "FROM tests t " +
                               "WHERE  l.LAB_ID = ";
              
        
        // Creating a DefaultTableModel to hold the table data
            DefaultTableModel model = (DefaultTableModel) labTestTable.getModel();
        model.setRowCount(0); // Clear existing rows if any

        pstmt = conn.prepareStatement(fetchTestData);
        rs = pstmt.executeQuery();
        
        // Fetching data from ResultSet and adding to JTable
         while (rs.next()) {
            int testId = rs.getInt("testId");
            String testName = rs.getString("testName");
            int testDuration = rs.getInt("testDuration");
            double testCost = rs.getDouble("testCost");
            String labName = rs.getString("labName");

            // Adding row to table model
            model.addRow(new Object[]{testId, testName, testDuration, testCost, labName});
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    } finally {
        // Close resources
        DatabaseUtil.close(conn, pstmt, rs);
    }
}

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(labTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(labTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(labTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(labTests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new labTests().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable labTestTable;
    // End of variables declaration//GEN-END:variables
}
